matches = [
    {
        "id": 9606860,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": "Facebook is the world's largest social network, with over 1 billion monthly active users.\n\nFacebook was founded by Mark Zuckerberg in February 2004, initially as an exclusive network for Harvard students. It was a huge hit: in 2 weeks, half of the schools in the Boston area began demanding a Facebook network. Zuckerberg immediately recruited his friends Dustin Moskovitz, Chris Hughes, and Eduardo Saverin to help build Facebook, and within four months, Facebook added 30 more college networks. \n\nThe original idea for the term Facebook came from Zuckerberg's high school (Phillips Exeter Academy). The Exeter Face Book was passed around to every student as a way for students to get to know their classmates for the following year. It was a physical paper book until Zuckerberg brought it to the internet.\n\nWith this success, Zuckerberg, Moskowitz and Hughes moved out to Palo Alto for the summer and rented a sublet. A few weeks later, Zuckerberg ran into the former cofounder of Napster, Sean Parker. Parker soon moved in to Zuckerberg's apartment and they began working together.  Parker provided the introduction to their first investor, Peter Thiel, cofounder of PayPal and managing partner of The Founders Fund. Thiel invested $500,000 into Facebook. \n\nWith millions more users, Friendster attempted to acquire the company for $10 million in mid 2004. Facebook turned down the offer and subsequently received $12.7 million in funding from Accel Partners, at a valuation of around $100 million. Facebook continued to grow, opening up to high school students in September 2005 and adding an immensely popular photo sharing feature the next month. The next spring, Facebook received $25 million in funding from Greylock Partners and Meritech Capital, as well as previous investors Accel Partners and Peter Thiel. The pre-money valuation for this deal was about $525 million. Facebook subsequently opened up to work networks, eventually amassing over 20,000 work networks. Finally in September 2006, Facebook opened to anyone with an email address. \n\nIn the summer of 2006, Yahoo attempted to acquire the company for $1 billion dollars. Reports actually indicated that Zuckerberg made a verbal agreement to sell Facebook to Yahoo. A few days later when Yahoo's stock price took a dive, the offer was lowered to $800 million and Zuckerberg walked away from the deal.  Yahoo later offered $1 billion again, this time Zuckerberg turned Yahoo down and earned instant notoriety as the “kid” who turned down a billion. This was not the first time Zuckerberg turned down an acquisition offer; Viacom had previously unsuccessfully attempted to acquire the company for $750 million in March 2006. \n\nNot long after, in October 2007, Microsoft invested $240 million into Facebook for 1.6 percent of the company in. This meant a valuation of over $15 billion, making Facebook the 5th most valuable US Internet company, yet with only $150 million in annual revenue. Many explained Microsoft's decision as being solely driven by the desire to outbid Google.\n\nFacebook continued to receive funding, most notably in January 2011 receiving a $1.5 billion round, valuing the company at $50 billion. A year later, in February 2012, Facebook announced that it was filing for its long-anticipated initial public offering. The company went public on May 18, 2012, opening on the NASDAQ with shares trading at $42.05.\n\nOne sour note for Facebook has been the controversy with social network ConnectU. The founders of ConnectU, former classmates of Mark Zuckerberg at Harvard, allege that Zuckerberg stole their original source code for Facebook. The ordeal has gone to court, and has now been resolved. \n\nNotwithstanding this lingering controversy, Facebook's growth has been staggering. Facebook announced astonishing numbers in February 2012 upon filing for its IPO. Over 845 million users log into Facebook every month, and 483 million users log in daily. Mobile users now make up half of Facebook's user base, with 425 million monthly actives. Facebook also announced that by the end of 2011 there had been 100 billion friend connections, and in recent months users had been registering 2.7 billion Likes and Comments per day. Facebook is one of the most trafficked sites in the US, and its international growth has been impressive. Additionally, Facebook is the top photo sharing site with 250 million photos uploaded per day.\n\nFacebook users' passion—or addiction—to the site is unparalleled: more than half use the product every single day and users spend an average of 19 minutes a day on Facebook. The site's popularity has garnered it pop culture fame, so much so that in 2010 a feature film entitled The Social Network was released which chronicled Facebook's inception.\n\nIn its 2012 IPO filing, Facebook announced that it intends to grow in the near future by expanding its global user base, increasing engagement by developing new social tools, improving the mobile experience, and creating more value for advertisers and users.",
        "point_of_contact": None,
        "all_categories": None,
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": None,
        "country": None,
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "affinity",
        "data_source_id": "260472098",
        "ts_updated": "2021-06-28T13:37:10.088224",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": None,
        "domains": ["facebook.com"],
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "affinity_260472098",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 9606863,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": None,
        "all_categories": None,
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": None,
        "country": "United States of America",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "salesforce",
        "data_source_id": "0016A000004BMt9QAG",
        "ts_updated": "2021-06-28T13:37:10.088224",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": None,
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "salesforce_0016A000004BMt9QAG",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 9607268,
        "company_name": "Weave",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": "Facebook is the world''s largest social network, with over 1 billion monthly active users.\n\nFacebook was founded by Mark Zuckerberg in February 2004, initially as an exclusive network for Harvard students. It was a huge hit: in 2 weeks, half of the schools in the Boston area began demanding a Facebook network. Zuckerberg immediately recruited his friends Dustin Moskovitz, Chris Hughes, and Eduardo Saverin to help build Facebook, and within four months, Facebook added 30 more college networks. \n\nThe original idea for the term Facebook came from Zuckerberg''s high school (Phillips Exeter Academy). The Exeter Face Book was passed around to every student as a way for students to get to know their classmates for the following year. It was a physical paper book until Zuckerberg brought it to the internet.\n\nWith this success, Zuckerberg, Moskowitz and Hughes moved out to Palo Alto for the summer and rented a sublet. A few weeks later, Zuckerberg ran into the former cofounder of Napster, Sean Parker. Parker soon moved in to Zuckerberg''s apartment and they began working together.  Parker provided the introduction to their first investor, Peter Thiel, cofounder of PayPal and managing partner of The Founders Fund. Thiel invested $500,000 into Facebook. \n\nWith millions more users, Friendster attempted to acquire the company for $10 million in mid 2004. Facebook turned down the offer and subsequently received $12.7 million in funding from Accel Partners, at a valuation of around $100 million. Facebook continued to grow, opening up to high school students in September 2005 and adding an immensely popular photo sharing feature the next month. The next spring, Facebook received $25 million in funding from Greylock Partners and Meritech Capital, as well as previous investors Accel Partners and Peter Thiel. The pre-money valuation for this deal was about $525 million. Facebook subsequently opened up to work networks, eventually amassing over 20,000 work networks. Finally in September 2006, Facebook opened to anyone with an email address. \n\nIn the summer of 2006, Yahoo attempted to acquire the company for $1 billion dollars. Reports actually indicated that Zuckerberg made a verbal agreement to sell Facebook to Yahoo. A few days later when Yahoo''s stock price took a dive, the offer was lowered to $800 million and Zuckerberg walked away from the deal.  Yahoo later offered $1 billion again, this time Zuckerberg turned Yahoo down and earned instant notoriety as the “kid” who turned down a billion. This was not the first time Zuckerberg turned down an acquisition offer; Viacom had previously unsuccessfully attempted to acquire the company for $750 million in March 2006. \n\nNot long after, in October 2007, Microsoft invested $240 million into Facebook for 1.6 percent of the company in. This meant a valuation of over $15 billion, making Facebook the 5th most valuable US Internet company, yet with only $150 million in annual revenue. Many explained Microsoft''s decision as being solely driven by the desire to outbid Google.\n\nFacebook continued to receive funding, most notably in January 2011 receiving a $1.5 billion round, valuing the company at $50 billion. A year later, in February 2012, Facebook announced that it was filing for its long-anticipated initial public offering. The company went public on May 18, 2012, opening on the NASDAQ with shares trading at $42.05.\n\nOne sour note for Facebook has been the controversy with social network ConnectU. The founders of ConnectU, former classmates of Mark Zuckerberg at Harvard, allege that Zuckerberg stole their original source code for Facebook. The ordeal has gone to court, and has now been resolved. \n\nNotwithstanding this lingering controversy, Facebook''s growth has been staggering. Facebook announced astonishing numbers in February 2012 upon filing for its IPO. Over 845 million users log into Facebook every month, and 483 million users log in daily. Mobile users now make up half of Facebook''s user base, with 425 million monthly actives. Facebook also announced that by the end of 2011 there had been 100 billion friend connections, and in recent months users had been registering 2.7 billion Likes and Comments per day. Facebook is one of the most trafficked sites in the US, and its international growth has been impressive. Additionally, Facebook is the top photo sharing site with 250 million photos uploaded per day.\n\nFacebook users'' passion—or addiction—to the site is unparalleled: more than half use the product every single day and users spend an average of 19 minutes a day on Facebook. The site''s popularity has garnered it pop culture fame, so much so that in 2010 a feature film entitled The Social Network was released which chronicled Facebook''s inception.\n\nIn its 2012 IPO filing, Facebook announced that it intends to grow in the near future by expanding its global user base, increasing engagement by developing new social tools, improving the mobile experience, and creating more value for advertisers and users.",
        "point_of_contact": None,
        "all_categories": None,
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": None,
        "country": None,
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "affinity",
        "data_source_id": "282040884",
        "ts_updated": "2021-06-28T13:37:10.088224",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "0a3916d74d03da4fb728755abbe5ec84",
            "b26d302163379e8f21a030e5cffb8717",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": None,
        "domains": ["facebook.com", "wwww.facebook.com"],
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "affinity_282040884",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11138849,
        "company_name": "Facebook",
        "website": None,
        "brief_description": None,
        "full_description": None,
        "point_of_contact": None,
        "all_categories": None,
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": None,
        "country": None,
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "affinity",
        "data_source_id": "136318954",
        "ts_updated": "2021-11-02T17:09:03.908858",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": ["0769afa2e0d5d4aebd39584bd13f4bea"],
        "array_hash_name": ["company_name_hash"],
        "investor_type": None,
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "affinity_136318954",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11139550,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": "Facebook is the world's largest social network, with over 1 billion monthly active users.\n\nFacebook was founded by Mark Zuckerberg in February 2004, initially as an exclusive network for Harvard students. It was a huge hit: in 2 weeks, half of the schools in the Boston area began demanding a Facebook network. Zuckerberg immediately recruited his friends Dustin Moskovitz, Chris Hughes, and Eduardo Saverin to help build Facebook, and within four months, Facebook added 30 more college networks. \n\nThe original idea for the term Facebook came from Zuckerberg's high school (Phillips Exeter Academy). The Exeter Face Book was passed around to every student as a way for students to get to know their classmates for the following year. It was a physical paper book until Zuckerberg brought it to the internet.\n\nWith this success, Zuckerberg, Moskowitz and Hughes moved out to Palo Alto for the summer and rented a sublet. A few weeks later, Zuckerberg ran into the former cofounder of Napster, Sean Parker. Parker soon moved in to Zuckerberg's apartment and they began working together.  Parker provided the introduction to their first investor, Peter Thiel, cofounder of PayPal and managing partner of The Founders Fund. Thiel invested $500,000 into Facebook. \n\nWith millions more users, Friendster attempted to acquire the company for $10 million in mid 2004. Facebook turned down the offer and subsequently received $12.7 million in funding from Accel Partners, at a valuation of around $100 million. Facebook continued to grow, opening up to high school students in September 2005 and adding an immensely popular photo sharing feature the next month. The next spring, Facebook received $25 million in funding from Greylock Partners and Meritech Capital, as well as previous investors Accel Partners and Peter Thiel. The pre-money valuation for this deal was about $525 million. Facebook subsequently opened up to work networks, eventually amassing over 20,000 work networks. Finally in September 2006, Facebook opened to anyone with an email address. \n\nIn the summer of 2006, Yahoo attempted to acquire the company for $1 billion dollars. Reports actually indicated that Zuckerberg made a verbal agreement to sell Facebook to Yahoo. A few days later when Yahoo's stock price took a dive, the offer was lowered to $800 million and Zuckerberg walked away from the deal.  Yahoo later offered $1 billion again, this time Zuckerberg turned Yahoo down and earned instant notoriety as the “kid” who turned down a billion. This was not the first time Zuckerberg turned down an acquisition offer; Viacom had previously unsuccessfully attempted to acquire the company for $750 million in March 2006. \n\nNot long after, in October 2007, Microsoft invested $240 million into Facebook for 1.6 percent of the company in. This meant a valuation of over $15 billion, making Facebook the 5th most valuable US Internet company, yet with only $150 million in annual revenue. Many explained Microsoft's decision as being solely driven by the desire to outbid Google.\n\nFacebook continued to receive funding, most notably in January 2011 receiving a $1.5 billion round, valuing the company at $50 billion. A year later, in February 2012, Facebook announced that it was filing for its long-anticipated initial public offering. The company went public on May 18, 2012, opening on the NASDAQ with shares trading at $42.05.\n\nOne sour note for Facebook has been the controversy with social network ConnectU. The founders of ConnectU, former classmates of Mark Zuckerberg at Harvard, allege that Zuckerberg stole their original source code for Facebook. The ordeal has gone to court, and has now been resolved. \n\nNotwithstanding this lingering controversy, Facebook's growth has been staggering. Facebook announced astonishing numbers in February 2012 upon filing for its IPO. Over 845 million users log into Facebook every month, and 483 million users log in daily. Mobile users now make up half of Facebook's user base, with 425 million monthly actives. Facebook also announced that by the end of 2011 there had been 100 billion friend connections, and in recent months users had been registering 2.7 billion Likes and Comments per day. Facebook is one of the most trafficked sites in the US, and its international growth has been impressive. Additionally, Facebook is the top photo sharing site with 250 million photos uploaded per day.\n\nFacebook users' passion—or addiction—to the site is unparalleled: more than half use the product every single day and users spend an average of 19 minutes a day on Facebook. The site's popularity has garnered it pop culture fame, so much so that in 2010 a feature film entitled The Social Network was released which chronicled Facebook's inception.\n\nIn its 2012 IPO filing, Facebook announced that it intends to grow in the near future by expanding its global user base, increasing engagement by developing new social tools, improving the mobile experience, and creating more value for advertisers and users.",
        "point_of_contact": None,
        "all_categories": None,
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": None,
        "country": None,
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "affinity",
        "data_source_id": "282281975",
        "ts_updated": "2021-11-02T17:50:50.634695",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": None,
        "domains": ["thefind.com", "facebook.com"],
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "affinity_282281975",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11241825,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "sw.saurabhw@gmail.com",
        "all_categories": [
            "Artificial Intelligence & Machine Learning",
            "Consumer Software",
            "Finance",
            "Marketplace",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": None,
        "country": None,
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "73225088708",
        "ts_updated": "2021-12-05T00:01:36.67401",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_73225088708",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11242002,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "salomon.aiach@gmail.com",
        "all_categories": [
            "Artificial Intelligence & Machine Learning",
            "Consumer Software",
            "E-Commerce",
            "Enterprise Software",
            "Finance",
            "Fintech",
            "Insurtech",
            "Payments",
            "SaaS",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Paris",
        "state_province": None,
        "country": "France",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "585968416754",
        "ts_updated": "2021-12-05T00:02:14.508554",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "e80ea430e4f2c37bb1e8e7c85df8be0f",
            "ba8c76c8dfc47ffc742178643fd29a22",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_585968416754",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11242069,
        "company_name": "Facebook",
        "website": "developers.facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "fabio.maffioli@gmail.com",
        "all_categories": ["E-Commerce"],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "London",
        "state_province": None,
        "country": "United Kingdom of Great Britain and Northern Ireland",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "333729765788",
        "ts_updated": "2021-12-05T00:02:29.255662",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9f0a28b8ca57a56f8011152cfe13cf87",
            "57880f4f0815f2f70041f70ff788e92a",
            "a6c6c3c1976144aa69e34b21b2bec04a",
            "27a74b55a5eeb455126dce4f4d6ec8df",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Corporate Venture Capital"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_333729765788",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11242445,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "khalid.ashour@gmail.com",
        "all_categories": [
            "Consumer Software",
            "Developer Tools",
            "Finance",
            "Marketplace",
            "Professional Services",
            "SaaS",
            "Transportation",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": "New York",
        "country": "United States of America",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "900059140669",
        "ts_updated": "2021-12-05T00:03:46.717937",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_900059140669",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11242616,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "sfarooqui@gmail.com",
        "all_categories": [
            "Artificial Intelligence & Machine Learning",
            "Fashion",
            "Gaming",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Singapore",
        "state_province": None,
        "country": "Singapore",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "443757194523",
        "ts_updated": "2021-12-05T00:04:15.850107",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "686030348dc9b99c50cea8915b432757",
            "2b99c7e1927fb336bac427cdb2ca997e",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_443757194523",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11244181,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "sw.saurabhw@gmail.com",
        "all_categories": [
            "Advertising",
            "Artificial Intelligence & Machine Learning",
            "E-Commerce",
            "Education",
            "Energy",
            "Lending",
            "Marketplace",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Seattle",
        "state_province": "Washington",
        "country": "United States of America",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "634832974446",
        "ts_updated": "2021-12-05T00:09:02.821897",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "4ce94aed03af52eeb5522e89209d6921",
            "0428e149e037c02813de9950fdf15f9f",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_634832974446",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11342164,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": "Social network",
        "full_description": "Facebook is the world's largest social network, with over 1 billion monthly active users.\n\nFacebook was founded by Mark Zuckerberg in February 2004, initially as an exclusive network for Harvard students. It was a huge hit: in 2 weeks, half of the schools in the Boston area began demanding a Facebook network. Zuckerberg immediately recruited his friends Dustin Moskovitz, Chris Hughes, and Eduardo Saverin to help build Facebook, and within four months, Facebook added 30 more college networks. \n\nThe original idea for the term Facebook came from Zuckerberg's high school (Phillips Exeter Academy). The Exeter Face Book was passed around to every student as a way for students to get to know their classmates for the following year. It was a physical paper book until Zuckerberg brought it to the internet.\n\nWith this success, Zuckerberg, Moskowitz and Hughes moved out to Palo Alto for the summer and rented a sublet. A few weeks later, Zuckerberg ran into the former cofounder of Napster, Sean Parker. Parker soon moved in to Zuckerberg's apartment and they began working together.  Parker provided the introduction to their first investor, Peter Thiel, cofounder of PayPal and managing partner of The Founders Fund. Thiel invested $500,000 into Facebook. \n\nWith millions more users, Friendster attempted to acquire the company for $10 million in mid 2004. Facebook turned down the offer and subsequently received $12.7 million in funding from Accel Partners, at a valuation of around $100 million. Facebook continued to grow, opening up to high school students in September 2005 and adding an immensely popular photo sharing feature the next month. The next spring, Facebook received $25 million in funding from Greylock Partners and Meritech Capital, as well as previous investors Accel Partners and Peter Thiel. The pre-money valuation for this deal was about $525 million. Facebook subsequently opened up to work networks, eventually amassing over 20,000 work networks. Finally in September 2006, Facebook opened to anyone with an email address. \n\nIn the summer of 2006, Yahoo attempted to acquire the company for $1 billion dollars. Reports actually indicated that Zuckerberg made a verbal agreement to sell Facebook to Yahoo. A few days later when Yahoo's stock price took a dive, the offer was lowered to $800 million and Zuckerberg walked away from the deal.  Yahoo later offered $1 billion again, this time Zuckerberg turned Yahoo down and earned instant notoriety as the “kid” who turned down a billion. This was not the first time Zuckerberg turned down an acquisition offer; Viacom had previously unsuccessfully attempted to acquire the company for $750 million in March 2006. \n\nNot long after, in October 2007, Microsoft invested $240 million into Facebook for 1.6 percent of the company in. This meant a valuation of over $15 billion, making Facebook the 5th most valuable US Internet company, yet with only $150 million in annual revenue. Many explained Microsoft's decision as being solely driven by the desire to outbid Google.\n\nFacebook continued to receive funding, most notably in January 2011 receiving a $1.5 billion round, valuing the company at $50 billion. A year later, in February 2012, Facebook announced that it was filing for its long-anticipated initial public offering. The company went public on May 18, 2012, opening on the NASDAQ with shares trading at $42.05.\n\nOne sour note for Facebook has been the controversy with social network ConnectU. The founders of ConnectU, former classmates of Mark Zuckerberg at Harvard, allege that Zuckerberg stole their original source code for Facebook. The ordeal has gone to court, and has now been resolved. \n\nNotwithstanding this lingering controversy, Facebook's growth has been staggering. Facebook announced astonishing numbers in February 2012 upon filing for its IPO. Over 845 million users log into Facebook every month, and 483 million users log in daily. Mobile users now make up half of Facebook's user base, with 425 million monthly actives. Facebook also announced that by the end of 2011 there had been 100 billion friend connections, and in recent months users had been registering 2.7 billion Likes and Comments per day. Facebook is one of the most trafficked sites in the US, and its international growth has been impressive. Additionally, Facebook is the top photo sharing site with 250 million photos uploaded per day.\n\nFacebook users' passion—or addiction—to the site is unparalleled: more than half use the product every single day and users spend an average of 19 minutes a day on Facebook. The site's popularity has garnered it pop culture fame, so much so that in 2010 a feature film entitled The Social Network was released which chronicled Facebook's inception.\n\nIn its 2012 IPO filing, Facebook announced that it intends to grow in the near future by expanding its global user base, increasing engagement by developing new social tools, improving the mobile experience, and creating more value for advertisers and users.",
        "point_of_contact": None,
        "all_categories": None,
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Menlo Park",
        "state_province": "California",
        "country": "United States of America",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "aim",
        "data_source_id": "001E000000SFfkOIAT",
        "ts_updated": "2021-12-09T14:32:48.22",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "669af199370409ea9bc86d61b3b869bd",
            "6d68bb28bd0d57a5dbe3552dd918edca",
            "8e6da0e08fee53fceed4bcfebd78811b",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "legacy_id_hash",
            "company_name_hash",
        ],
        "investor_type": None,
        "domains": None,
        "social_media_profiles": [
            "https://twitter.com/facebook",
            "https://angel.co/facebook",
        ],
        "legacy_id": "001E000000SFfkOIAT",
        "demo_day_pitch_video_url": None,
        "logo_url": "https://s3.amazonaws.com/photos.angel.co/startups/i/32167-783be84a29fcf36b3429c4fab546e9bf-medium_jpg.jpg?buster=1326842418",
        "twitter_url": "twitter.com/facebook",
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": "crunchbase.com/organization/facebook",
        "pitchbook_url": None,
        "angellist_url": "angel.co/facebook",
        "phone_mobile": None,
        "data_source_key": "aim_001E000000SFfkOIAT",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11760670,
        "company_name": "Facebook",
        "website": "developers.facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "fabio.maffioli@gmail.com",
        "all_categories": ["E-Commerce"],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "London",
        "state_province": None,
        "country": "United Kingdom of Great Britain and Northern Ireland",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "640192253015",
        "ts_updated": "2022-01-23T00:03:44.842013",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9f0a28b8ca57a56f8011152cfe13cf87",
            "57880f4f0815f2f70041f70ff788e92a",
            "a6c6c3c1976144aa69e34b21b2bec04a",
            "27a74b55a5eeb455126dce4f4d6ec8df",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Corporate Venture Capital"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_640192253015",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11761400,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "sw.saurabhw@gmail.com",
        "all_categories": [
            "Artificial Intelligence & Machine Learning",
            "Consumer Software",
            "Finance",
            "Marketplace",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Seattle",
        "state_province": "Washington",
        "country": "United States of America",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "73749487132",
        "ts_updated": "2022-01-23T00:04:41.238028",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "4ce94aed03af52eeb5522e89209d6921",
            "0428e149e037c02813de9950fdf15f9f",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_73749487132",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11761560,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "salomon.aiach@gmail.com",
        "all_categories": [
            "Artificial Intelligence & Machine Learning",
            "Consumer Software",
            "E-Commerce",
            "Enterprise Software",
            "Finance",
            "Fintech",
            "Insurtech",
            "Payments",
            "SaaS",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Paris",
        "state_province": None,
        "country": "France",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "871621369288",
        "ts_updated": "2022-01-23T00:04:49.032003",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "e80ea430e4f2c37bb1e8e7c85df8be0f",
            "ba8c76c8dfc47ffc742178643fd29a22",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_871621369288",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11762318,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "zhanguang07@gmail.com",
        "all_categories": ["Advertising", "E-Commerce", "Gaming"],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": None,
        "country": "Singapore",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "799217228703",
        "ts_updated": "2022-01-23T00:05:36.782883",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_799217228703",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11762350,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "sfarooqui@gmail.com",
        "all_categories": [
            "Artificial Intelligence & Machine Learning",
            "Fashion",
            "Gaming",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Singapore",
        "state_province": None,
        "country": "Singapore",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "885223299161",
        "ts_updated": "2022-01-23T00:05:38.463594",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "686030348dc9b99c50cea8915b432757",
            "2b99c7e1927fb336bac427cdb2ca997e",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_885223299161",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11762830,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "khalid.ashour@gmail.com",
        "all_categories": [
            "Consumer Software",
            "Developer Tools",
            "Finance",
            "Marketplace",
            "Professional Services",
            "SaaS",
            "Transportation",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": None,
        "state_province": "New York",
        "country": "United States of America",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "486038210283",
        "ts_updated": "2022-01-23T00:06:05.921027",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_486038210283",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
    {
        "id": 11763539,
        "company_name": "Facebook",
        "website": "facebook.com",
        "brief_description": None,
        "full_description": None,
        "point_of_contact": "vleung5@gmail.com",
        "all_categories": [
            "Artificial Intelligence & Machine Learning",
            "Finance",
            "Fintech",
            "Payments",
            "SaaS",
        ],
        "operating_status": None,
        "funding_stage": None,
        "total_raised": None,
        "email_contact_internal": None,
        "street_add_1": None,
        "street_add_2": None,
        "city": "Minneapolis",
        "state_province": "Minnesota",
        "country": "United States of America",
        "mailing_code": None,
        "year_founded": None,
        "active_investors": None,
        "data_source": "airtable_investors",
        "data_source_id": "522015250155",
        "ts_updated": "2022-01-23T00:06:49.7362",
        "aliases": None,
        "funding_series": None,
        "funding_type": None,
        "array_hash": [
            "9c709108dcc53587a617f997780e64fd",
            "6d843487b105d5276f54908af7d59139",
            "a676cfeda24407e842de781239ab5e90",
            "7cebc395deff19664c804f528c65cc43",
            "0769afa2e0d5d4aebd39584bd13f4bea",
        ],
        "array_hash_name": [
            "website_hash",
            "website_company_name_hash",
            "website_city_hash",
            "company_name_city_hash",
            "company_name_hash",
        ],
        "investor_type": ["Angel"],
        "domains": None,
        "social_media_profiles": None,
        "legacy_id": None,
        "demo_day_pitch_video_url": None,
        "logo_url": None,
        "twitter_url": None,
        "linkedin_url": None,
        "facebook_url": None,
        "crunchbase_url": None,
        "pitchbook_url": None,
        "angellist_url": None,
        "phone_mobile": None,
        "data_source_key": "airtable_investors_522015250155",
        "legal_name": None,
        "registered_address": None,
        "registered_country": None,
        "annual_revenue": None,
        "number_of_employees": None,
        "industry_website": None,
        "last_raise_amount": None,
        "last_raise_date": None,
        "number_of_customers": None,
        "runway": None,
        "md_id": None,
        "session": None,
        "demo_day_pitch_deck_url": None,
        "seeking_capital": None,
        "paperstreet_url": None,
        "ts_status": None,
    },
]
